### PR TITLE
supress the output of run_tests

### PR DESCRIPTION
**Pull request by k-okada**
hope this solves https://github.com/start-jsk/jsk_apc/pull/2697#issuecomment-544828515
Cc: @pazeshun

### CODE REVIEW

**Comment by pazeshun** [comment]
@k-okada Thank you. I'll try to use this.

**Comment by pazeshun** [comment]
@k-okada I think this PR includes typos.
Please check https://github.com/k-okada/jsk_travis/pull/1

**Comment by pazeshun** [comment]
With this PR and https://github.com/k-okada/jsk_travis/pull/1, travis test of https://github.com/start-jsk/jsk_apc/pull/2697 passed thanks to short log.

For comparison, I extracted logs about testing `jsk_apc2016_common`.
Logs before this PR (extracted from https://api.travis-ci.org/v3/job/601132003/log.txt):
https://gist.github.com/pazeshun/3385e4dfd6ead8d1b4372c1472572fce
Logs after this PR (extracted from https://api.travis-ci.org/v3/job/601276340/log.txt):
https://gist.github.com/pazeshun/57c7446dee307077842ce98b2f0fe66b

I found that some logs are missing in new log.
For example,
```
[jsk_apc2016_common:make] /usr/bin/cmake -H/home/travis/ros/ws_jsk_apc/src/jsk_apc/jsk_apc2016_common -B/home/travis/ros/ws_jsk_apc/build/jsk_apc2016_common --check-build-system CMakeFiles/Makefile.cmake 0
```
```
[jsk_apc2016_common:make] make[1]: Entering directory `/home/travis/ros/ws_jsk_apc/build/jsk_apc2016_common'
```
```
[jsk_apc2016_common:make] Dependee "/home/travis/ros/ws_jsk_apc/build/jsk_apc2016_common/CMakeFiles/clean_test_results_jsk_apc2016_common.dir/DependInfo.cmake" is newer than depender "/home/travis/ros/ws_jsk_apc/build/jsk_apc2016_common/CMakeFiles/clean_test_results_jsk_apc2016_common.dir/depend.internal".
```

**Comment by pazeshun** [comment]
@k-okada Could you merge and release this?

**Comment by k-okada** [comment]
released 0.5.4

**Pull request merged**
