### PR TITLE
[travis.sh] catkin build --no-color for logs easy to be read

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
I think this makes it easy to read the log file.
like: https://s3.amazonaws.com/archive.travis-ci.org/jobs/68918914/log.txt

it will change
` [34m[1mLLVM version[0m` -> `LLVM version`

**Comment by k-okada** [comment]
someone likes color -> https://github.com/jsk-ros-pkg/jsk_travis/issues/13, 
please discuss...

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Okay.

**Comment by wkentaro** [comment]
I found the main factor which makes the log hard to read is `catkin build`'s status line.
color output may be okay if I use `less` to view.

Firstly, please see: https://github.com/jsk-ros-pkg/jsk_travis/pull/72#issuecomment-118671623

**Comment by garaemon** [comment]
build log without color is ok to me.
https://github.com/jsk-ros-pkg/jsk_travis/issues/13 was important to correctly escape color code and if we can remove it, it's ok.

**Comment by wkentaro** [comment]
I found `$ cat logs.txt` work for me (with cosmetic output).

I found travis-cli at https://github.com/travis-ci/travis.rb .
and `$ travis logs` is useful.

So I close this. Thanks.

**Pull request closed without merging**
