### PR TITLE
Cache pip downloaded tgz on jenkins

### PR DESCRIPTION
**Pull request by wkentaro**
For #207

### CODE REVIEW

**Comment by wkentaro** [comment]
?
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-18.8-py2.7.egg'
```

**Comment by snozawa** [comment]
Recently travis build image was upgraded and almost all jsk's travis fail from similar error.
Could you try https://github.com/jsk-ros-pkg/jsk_robot/pull/523#issuecomment-164707925 in this PR just for test?

**Comment by wkentaro** [comment]
Thanks for your informatiion.
I don't know the reason why this error occurs, but we can fix this in the future, after using the new travis platform for a while.

**Comment by k-okada** [comment]
ubuntu uses different pip version, are you proposing that jsk_* users need to install pip from pypy, other than default ros install process -> http://wiki.ros.org/indigo/Installation/Ubuntu
http://packages.ubuntu.com/trusty-updates/python-pip

**Comment by wkentaro** [comment]
Yeah, because rosdep required the latest pip at a time.
Currently I think it is fixed.

**Comment by k-okada** [comment]
but current rosdep does not work with apt installed pip, because of
https://github.com/jsk-ros-pkg/jsk_recognition/issues/1874#issuecomment-250906422,
and this depends on how rosdep maintainer thinks, but we need to decide
whether
1. rosdep needs to run with apt installed pip
2. define recommended version of pip
3. assuming all users has always upgrade to latest pip


--
◉ Kei Okada


2016-10-01 22:07 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Pull request merged**
