### PR TITLE
[WIP] Force to set devel/.catkin

### PR DESCRIPTION
**Pull request by wkentaro**
Issue: https://github.com/catkin/catkin_tools/issues/283

### CODE REVIEW

**Comment by wkentaro** [comment]
To fix https://github.com/start-jsk/jsk_apc/issues/1256

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this, if it looks good!

**Comment by wkentaro** [comment]
maybe upgrading catkin_tools fixes this issue.

**Comment by k-okada** [comment]
I think the problems is if there are two catkin are running, one catkin create `.catkin` but another one did not notice that and create the '.catkin' file again, instead of append to the '.catkin'
https://github.com/ros/catkin/pull/671/files#diff-4711d7d40543d1cda255cb4f83806100R23
https://github.com/ros/catkin/issues/670

**Comment by wkentaro** [comment]
It is closed, but not fixed?

--
和田 健太郎 / Kentaro Wada
http://wkentaro.com/

2016年4月14日 20:50 +0900 に Kei Okada<notifications@github.com>は書きました:

**Pull request closed without merging**
