### PR TITLE
Show progressbar for Jenkins job

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
```

next build number is 2022
wait for trusty-travis-jsk-ros-pkg-jsk_travis-indigo-deb-true 2022
start building, wait for result....

 35% (0 of 1) |#########                   | Elapsed Time: 0:00:00 ETA:  0:00:00
                                                                                
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_travis-indigo-deb-true/2022/ building.. True result... None

 52% (0 of 1) |##############              | Elapsed Time: 0:00:30 ETA:  0:02:20
 69% (0 of 1) |###################         | Elapsed Time: 0:01:00 ETA:  0:01:55
 86% (0 of 1) |########################    | Elapsed Time: 0:01:31 ETA:  0:01:26
100% (1 of 1) |############################| Elapsed Time: 0:02:01 ETA:  0:01:05
100% (1 of 1) |############################| Elapsed Time: 0:02:31 Time: 0:02:31
Started by user k-okada
```

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
need rebsae

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
sorry there is a collisoin

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
