### PR TITLE
Use rostest with --text option

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
http://wiki.ros.org/rostest/Commandline says
```
--text
Sends console output to screen instead XML test result file. IMPORTANT:
when you run this option, the XML test result file will not be produced, so
this is for command-line debugging only.
```


--
◉ Kei Okada

**Comment by wkentaro** [comment]
How to show the test results even when rostest fails?
currently no verbose output: https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/84864867

**Comment by k-okada** [comment]
we'd put
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L213 within
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L35,
originally this part is designed as execute in `after_failure` section of
travis.yml

--
◉ Kei Okada

**Comment by wkentaro** [comment]
should I send pr? or you do?

**Pull request closed without merging**
