### PR TITLE
use .travis.rosinstall when USE_DEB != true

### PR DESCRIPTION
**Pull request by furushchev**
- refactor `if` condition
- use `.travis.rosinstall` when `USE_DEB != true` (before this PR, `.travis.rosinstall` is not used when `USE_DEB = source`)

### CODE REVIEW

**Comment by wkentaro** [comment]
LGTM :+1:

**Comment by k-okada** [comment]
LNGTM :-1: USE_DEB can have true, false and source. should be fied in #190

**Comment by wkentaro** [comment]
I think he knew about it. 
so what USE_DEB=source is for?

**Comment by k-okada** [comment]
`USE_DEB=source` uses https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/setup_upstream.sh, wehre as `USE_DEB=false` uses https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/.travis.rosinstall

since https://github.com/euslisp/EusLisp does not contain ros-related files such as package.xml and CMakeLists.txt, we'll use http://github.com/tork-a/euslisp-release for `USE_DEB=false`, where as `USE_DEB=source` uses https://github.com/euslisp/EusLisp

**Comment by wkentaro** [comment]
I see. Now this not necessary.
"Sorry" by @furushchev

**Comment by k-okada** [comment]
is fixed in #190, refactor code is always a good thing. do not mind.

**Pull request merged**
