### PR TITLE
Use X server of travis node

### PR DESCRIPTION
**Pull request by furushchev**
Some servers on travis fails to bootup X server.
(I suspect that newer version of travis worker prevents launching X server on docker on travis)
So I changed to start X server on host side and use it through docker.

Also add test that uses camera plugin that needs screen rendering.

### CODE REVIEW

**Comment by furushchev** [comment]
It looks that after jade we cannot test camera image on gazebo installable from ros repo.
https://bitbucket.org/osrf/gazebo/issues/1837/vmware-rendering-z-ordering-appears-random

**Comment by furushchev** [comment]
For testing gazebo on travis / jenkins with ROS jade or later, we will have to add gazebo ppa and use the latest gazebo (>= 7.4.0). (for detail please see the link I posted)
@k-okada How do you think of it?

**Comment by k-okada** [comment]
at this moment, we can skip gazebo test for J/K/...

--
◉ Kei Okada


2017-02-16 20:11 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada OK.

**Comment by k-okada** [comment]
@furushchev  we found we need to shutdown X server on travis test -> https://github.com/jsk-ros-pkg/jsk_roseus/pull/527
This only happens on master branch and all master branch has been failed (https://travis-ci.org/jsk-ros-pkg/jsk_roseus/branches), until we merge https://github.com/jsk-ros-pkg/jsk_roseus/pull/527
I'm not sure why this happens only jsk_roseus repository, but if we found similar problem on other packages, we'd better to stop X server end of travis.sh file

**Comment by furushchev** [comment]
@k-okada Thank you for information! We also use X server on other projects (to run gazebo) and we don't yet see this problem, but if I find any other information, let you know. :+1:

**Comment by furushchev** [comment]
@k-okada Is it better to create PR to stop X server for `jsk_travis`?

**Pull request merged**
