### PR TITLE
[travis_watchdog.py] add watchdog for travis and kill orphan docker container on jenkins

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
Btw, did you realize that there is a lot of docker_ps_a.txt files under tmp directory?

**Comment by furushchev** [comment]
@k-okada No, how can we use them?

**Comment by k-okada** [comment]
I thought you have used this file before... 
```
4.0K	/tmp/77393.docker_ps_a.txt
4.0K	/tmp/77320.docker_ps_a.txt
4.0K	/tmp/77256.docker_ps_a.txt
4.0K	/tmp/76032.docker_ps_a.txt
4.0K	/tmp/758.docker_ps_a.txt
4.0K	/tmp/75830.docker_ps_a.txt
4.0K	/tmp/75504.docker_ps_a.txt
4.0K	/tmp/75095.docker_ps_a.txt
4.0K	/tmp/74918.docker_ps_a.txt
4.0K	/tmp/73847.docker_ps_a.txt
4.0K	/tmp/73752.docker_ps_a.txt
4.0K	/tmp/73216.docker_ps_a.txt
4.0K	/tmp/73169.docker_ps_a.txt
4.0K	/tmp/7282.docker_ps_a.txt
4.0K	/tmp/72014.docker_ps_a.txt
4.0K	/tmp/72013.docker_ps_a.txt
4.0K	/tmp/71859.docker_ps_a.txt
4.0K	/tmp/71752.docker_ps_a.txt
4.0K	/tmp/68834.docker_ps_a.txt
4.0K	/tmp/68625.docker_ps_a.txt
4.0K	/tmp/67941.docker_ps_a.txt
4.0K	/tmp/67572.docker_ps_a.txt
4.0K	/tmp/66906.docker_ps_a.txt
4.0K	/tmp/66733.docker_ps_a.txt
4.0K	/tmp/6656.docker_ps_a.txt
4.0K	/tmp/66182.docker_ps_a.txt
4.0K	/tmp/66145.docker_ps_a.txt
4.0K	/tmp/65881.docker_ps_a.txt
4.0K	/tmp/65815.docker_ps_a.txt
4.0K	/tmp/65656.docker_ps_a.txt
4.0K	/tmp/6529.docker_ps_a.txt
```
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/check_diskspace/2351/console

**Comment by furushchev** [comment]
@k-okada Oh, I don't remember... Maybe it is not me.

**Comment by furushchev** [comment]
@k-okada If I asked you to create these text files, I will no more use them, anyway thank you!

**Comment by k-okada** [comment]
The file is removed when we reboot jenkins server, but it appers again. and @wkentaro asked me about this file and I did not remember, so I asked you, but it seems @wkntaro's update.
The ' keep containers for a while' feature was originally introduced by @furushchev and @wkentaro has updated with docker_ps_a.txt file output, and now, may be this feature is not working and no one remember who is writing docker_ps_a.txt files...
I'm concerned that this PR (#317) also ends with same conclusion  
https://github.com/jsk-ros-pkg/jsk_travis/commit/ae71a798413c8603575de35770ec8c03d60a5a07
https://github.com/jsk-ros-pkg/jsk_travis/commit/be5a632999c069e107773b6a0347bee51bae0d89

**Comment by furushchev** [comment]
@k-okada Yes, updating is trade off of 'better experience' and 'unstable'. I'd like to just save time on each testing. Is there any possible solutions?

**Comment by k-okada** [comment]
please fix `/tmp/docker_ps_a.txt` problem first, then think about adding new feature.

**Comment by furushchev** [comment]
@k-okada thanks to https://github.com/jsk-ros-pkg/jsk_travis/pull/319 that problem is going to be fixed. Hmm, IMO, this is not relevant to this feature though. (This feature is for saving resource of jenkins, and the feature about `docker_ps_a` is for debugging test error at instance on jenkins.

**Pull request merged**
