### PR TITLE
Clean up dead docker containers

### PR DESCRIPTION
**Pull request by garaemon**
@k-okada please check this

### CODE REVIEW

**Comment by furushchev** [comment]
BTW, is there demand to debug by attaching docker container?
If so, it seems to be inconvenient to remove dead container immediately.
(possible solution is to remove from old container?)

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_travis/pull/98

humm, this was disabled a year ago....


--
◉ Kei Okada

**Comment by furushchev** [comment]
Is this still disabled?
If not, I think it's good to close.

**Comment by k-okada** [comment]
now docker is running with '--rm' option
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis_jenkins.py#L303

**Pull request closed without merging**
