### PR TITLE
use catkin_tools 0.3.1 for hydro

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by wkentaro** [comment]
Why do you use catkin_tools 0.3.1 on hydro?

`catkin build -i` won't display logs with catkin_tools 0.3.1, and it is difficult to debug the testing.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1673#issuecomment-220338520
https://github.com/jsk-ros-pkg/jsk_travis/blob/45f62ac0fb9e782f39debe971143274373d7f4b0/travis.sh#L188

**Comment by k-okada** [comment]
On 12.04 we still have to use 0.3.1
https://github.com/catkin/catkin_tools/issues/336

By the way, is it possible for pip to force install all dependency of catkin_tools 0.4.x ? 

--
◉ Kei Okada

2016/05/20 0:20、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
> By the way, is it possible for pip to force install all dependency of catkin_tools 0.4.x ?

What do you mean with `force`? You can reinstall all of the depends with `--ignore-installed` option.

**Comment by k-okada** [comment]
If any of dependent python module is installed via apt, pip did not install
them. Is it correct? if so, some module installed via apt was old for
latest catkin_tools

--
◉ Kei Okada

**Comment by wkentaro** [comment]
That depends on the declaration of requirements in setup.py of the python package.
If the depends are old which are installed via apt, pip automatically upgrade it.
https://github.com/catkin/catkin_tools/blob/master/setup.py#L13-L18

**Pull request merged**
