### PR TITLE
Install HEAD version rosdep to resolve python depends via rosdep

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by garaemon** [comment]
Is it required?

**Comment by wkentaro** [comment]
I need this commit at https://github.com/jsk-ros-pkg/jsk_common/pull/1120, because current rosdep does not work for python dependencies (which should be installed via rosdep & pip).
https://github.com/ros-infrastructure/rosdep/pull/411
And rosdep is not yet released since that commit.

**Comment by wkentaro** [comment]
rosdep 0.11.3 is released.

**Comment by k-okada** [comment]
just for note this is not head version, but
https://github.com/ros-infrastructure/rosdep/commit/4fda8f4c32464b6bb80a710cb86c0e969dbdc2c5
versoin. if you use 0.11.3, thta's ok.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Renamed title:

Install HEAD version rosdep to resolve python depends via rosdep
↓
Install rosdep from source (4fda8) to resolve python depends via rosdep

**Pull request closed without merging**
