### PR TITLE
Fix typo in generating job name: a-f -> a-z

### PR DESCRIPTION
**Pull request by wkentaro**
Just a typo. Sorry.

### CODE REVIEW

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by k-okada** [comment]
I did not know this is critical bug, and need to release asap

**Comment by wkentaro** [comment]
Sorry about it.
I'm not confident about it, but that is a possible problem.

**Comment by wkentaro** [comment]
Then, could you please release the hash https://github.com/jsk-ros-pkg/jsk_travis/commit/87d6ea61b59a848d35d014de5fb36cb9e504194b as 0.4.17?

**Comment by k-okada** [comment]
I'm waiting for #297 #298 #295 .
Btw why we can't catch this bug on test?

**Comment by wkentaro** [comment]
Because this bug don't happen always.
Even with the unreadable job name, some tests pass.
screen shot 2016-08-11 at 19 48 42

Also, I don't understand why the test fails with the unreadable job names.
So it is also possible this PR won't fix the issue.

**Pull request merged**
