### PR TITLE
Check version of ros tools

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge.

```
+ rosversion roslaunch

1.11.15

+ rosversion rospack

2.2.5

+ pip show rospkg

+ grep Version:

+ awk '{print $2}'

The directory '/workspace/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning

1.1

1.0.35
```

**Comment by k-okada** [comment]
does pip show version packages installed from apt-get?

**Comment by wkentaro** [comment]
In case the package is also released in pip, YES.
For `cv2` no, but `rospkg` is released in both `apt` and `pip`, so we can detect the version both `apt-cache showpkg` and `pip show`.

But In this case, we assume the `rospkg` is installed via `apt` so I will change it.

**Comment by wkentaro** [comment]
I updated the commit to check version with `apt-cache`.

**Comment by k-okada** [comment]
on ubuntu, installing package via pip will confuse users and systems, you
should install everything from apt
http://answers.ros.org/question/44186/how-do-i-solve-fuerte-overlay-creation-problem/

--
◉ Kei Okada

**Comment by wkentaro** [comment]
As far as I can, I do so.
But some times the package released on apt is too old. Like pip.
In that case I use pip because it is necessary.

2015年10月19日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> on ubuntu, installing package via pip will confuse users and systems, you
> should install everything from apt
>
> http://answers.ros.org/question/44186/how-do-i-solve-fuerte-overlay-creation-problem/
>
> --
> ◉ Kei Okada
>
>
> On Sun, Oct 18, 2015 at 3:09 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I updated the commit to check version with apt-cache.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_travis/pull/173#issuecomment-148981044>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/pull/173#issuecomment-149065503>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
@k-okada I'd like this is merged before next release.

**Comment by wkentaro** [comment]
Thanks. Please release another version.

**Comment by k-okada** [comment]
done

--
◉ Kei Okada

**Comment by wkentaro** [comment]
thanks :sparkles:

**Pull request merged**
