### PR TITLE
move git config --add safe.directory after chown

### PR DESCRIPTION
**Pull request by knorth55**
```
+ git config --global --add safe.directory /__w/jsk_travis/jsk_travis
error: could not lock config file /github/home/.gitconfig: Permission denied
```
https://github.com/jsk-ros-pkg/jsk_travis/runs/6121434102?check_suite_focus=true

This error does not causes CI error on `jsk_travis`, but  in repo with `submodules` like `jsk_apc`.
```
fatal: unsafe repository ('/__w/jsk_apc/jsk_apc' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/jsk_apc/jsk_apc
Error: Process completed with exit code 128.
```
https://github.com/start-jsk/jsk_apc/runs/6246483890?check_suite_focus=true

### CODE REVIEW

**Comment by knorth55** [comment]
```
fatal: unsafe repository ('/__w/jsk_apc/jsk_apc' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/jsk_apc/jsk_apc
```

hmmm, I still have error on submodules in noetic, I need to check more.

https://github.com/start-jsk/jsk_apc/runs/6246659126?check_suite_focus=true

**Comment by knorth55** [comment]
My workaround is adding these lines after `checkout` for `submodules`.
This might be useful for other repo with `submodules` like `jsk_apc`.

```yaml
      - name: Checkout
        uses: actions/checkout@v2
      - name: work around permission issue again
        run: |
          set -x
          grep path $GITHUB_WORKSPACE/.gitmodules | sed 's/.*=//' | xargs -n 1 -I '{}' git config --global --add safe.directory $GITHUB_WORKSPACE/'{}'
```

**Review by k-okada — COMMENTED** [review]
We have two strategy based on environment,  one for native github action's contianer, and another one is when  you use your own docker environment (or run script with user mode?), y

``` 
      - name: work around permission issue  # https://github.com/actions/checkout/issues/760#issuecomment-1097501613
        run: |
          set -x
          export USER=$(whoami)
          if [ "${{ matrix.CONTAINER }}" = "jskrobotics/ros-ubuntu:14.04" ]; then
             git config --global --add safe.directory $GITHUB_WORKSPACE || echo "OK" # Show 'could not lock config file /github/home/.gitconfig: Permission denied', but it is ok
             sudo mkdir -p /__w/
             sudo chmod 777 -R /__w/
             sudo chown -R $USER $HOME
             # sudo mkdir -p /home/runner/work/_temp/_github_workflow/
             # sudo chown -R $USER $HOME /home/runner/work/_temp/_github_workflow/
             # ls -al /home/runner/work/_temp/_github_workflow/
          else
             git config --global --add safe.directory $GITHUB_WORKSPACE
          fi
```

**Comment by knorth55** [comment]
I don't understand properly, 
but in order to avoid the permission problem, we first need to change the permission of the directory and then run `git config --global`.

**Pull request closed without merging**
