### PR TITLE
Stop using HEAD version catkin and use apt released one

### LINKED ISSUE #283: Why latest catkin is installed?
It seems that @k-okada changed it.
https://github.com/jsk-ros-pkg/jsk_travis/blame/master/travis.sh#L104

Installing HEAD version of catkin causes problems because of some api changes like:

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1784#issuecomment-233686059 
- https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/68
- https://github.com/jsk-ros-pkg/jsk_common/pull/1428

because of https://github.com/ros/catkin/pull/813 .

So I'm changing the `travis.sh` for installing `ros-${ROSDISTRO}-catkin` by apt.
Do you agree? @k-okada

### PR DESCRIPTION
**Pull request by wkentaro**
Close #283

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this and release next version. @k-okada

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by k-okada** [comment]
released

**Comment by wkentaro** [comment]
Thank you, but i found #285 is necessary, sorry.

**Pull request merged**
