### PR TITLE
Run .travis.before_XXX.sh script before travis_time_start

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
I do like to run arbitrary commands before each block `travis_time_start ~ travis_time_end`.

**Comment by k-okada** [comment]
variable such as BEFORE_SCRIPT  will provide similar function, so we need
to choose one of them

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I think the function of BEFORE_SCRIPT is poor, so it can removed.
What do you think? @k-okada

2015年11月9日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> variable such as BEFORE_SCRIPT will provide similar function, so we need
> to choose one of them
>
> --
> ◉ Kei Okada
>
>
> On Mon, Nov 9, 2015 at 2:17 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I do like to run arbitrary commands before each block travis_time_start ~
> > travis_time_end.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_travis/pull/192#issuecomment-154931528>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/pull/192#issuecomment-154992747>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
which case did you feel BEFORE_SCRIPT not working well.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> which case did you feel BEFORE_SCRIPT not working well.

like https://github.com/jsk-ros-pkg/jsk_travis/issues/171
so I can't believe it works personally :(

Also,
* we cannot environmental variable in `BEFORE_SCRIPT` like:
`BEFORE_SCRIPT="cd $CI_SOURCE_PATH; wget ...`
* and need to care about `"` or `'` like:
`BEFORE_SCRIPT="wget 'http://google.com' -O index.html"`

These are frustrating to me.

**What I want to do at this moment** is adding some tests for my package between below two lines:
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L212-L213

**Comment by wkentaro** [comment]
I need this feature at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1327/files .
Because in that PR, I need to install test data with rosrun command.

**Comment by wkentaro** [comment]
But `BEFORE_SCRIPT` is before `rosdep install` so `rosrun [the package]` does not work.

**Comment by wkentaro** [comment]
ping

**Comment by wkentaro** [comment]
ping

**Comment by k-okada** [comment]
i think this is too compilex

--
◉ Kei Okada

**Comment by wkentaro** [comment]
so, what do you think is alternative to as simple method?
My idea for this substitution is

* add env `BEFORE_CATKIN_RUNTESTS_SCRIPT`
* split travis.sh to setup_ros.sh, catkin_run_tests.sh, ... and source these script in travis.sh. (this is difficult to run test on jenkins)

**Comment by wkentaro** [comment]
Fixed by set execute_process to depend on test like https://github.com/jsk-ros-pkg/jsk_recognition/pull/1327/files#diff-250fce108c6e3969cbb9873e11c10453R527

**Comment by k-okada** [comment]
You can also take a look at this


http://docs.ros.org/jade/api/catkin/html/howto/format2/downloading_test_data.html



2015年11月25日水曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Closed #192 <https://github.com/jsk-ros-pkg/jsk_travis/pull/192>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/pull/192#event-474508380>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thanks. That's what you told me as a solution. 
But I needed to run some processings for the data. (like rosbag decompress)
So I could not use `catkin_download_test_data`...

**Comment by wkentaro** [comment]
One solution is to create a macro for that, But I thought that's too much.

**Pull request closed without merging**
