### PR TITLE
Run rostest again with --text option if the test failed

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #165
Closes #166

### CODE REVIEW

**Comment by wkentaro** [comment]
@k-okada 
Please review this.

**Comment by wkentaro** [comment]
ping

**Comment by k-okada** [comment]
It seems original code call error functioning failed, but this doesn't . Are you intend to do this?

**Comment by wkentaro** [comment]
> It seems original code call error functioning failed, but this doesn't . Are you intend to do this?

Thanks, I missed about it.

**Comment by wkentaro** [comment]
Please see another change.
https://github.com/jsk-ros-pkg/jsk_travis/pull/167/commits

**Comment by wkentaro** [comment]
@k-okada I'd like this is merged before next release.

**Pull request merged**
