### PR TITLE
[WIP] Add env BEFORE_RUNTESTS

### PR DESCRIPTION
**Pull request by wkentaro**
- [ ] reproduce the problem at local
- [ ] find the error's cause

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
when we need this?

**Comment by wkentaro** [comment]
I need this to fix this https://github.com/jsk-ros-pkg/jsk_travis/pull/238 , I added a program fixes the ROS_PACKAGE_PATH problem: https://github.com/start-jsk/jsk_apc/pull/1289 .

**Comment by k-okada** [comment]
ok,
1. can you reproduce this error on your local environment?
2. if so could you try with `--isolate-devel` https://github.com/k-okada/test_catkin_atomic/blob/master/.travis.yml#L10

**Comment by k-okada** [comment]
if it does not work well, how about `touch devel/.caktin' before `catkin build`, this works for all situations, so you do not have to add special code just for jsk_apc using  BEFORE_RUNTESTS

**Comment by wkentaro** [comment]
> 1. can you reproduce this error on your local environment?

It is rare, but I think I can reproduce it.
So, I'm trying to reproduce it constantly.

**Pull request closed without merging**
