### PR TITLE
Use snapshot of rosdep list on melodic

### PR DESCRIPTION
**Pull request by pazeshun**
After https://github.com/ros/rosdistro/pull/39174 was merged, rosdep key `python-omniorb` cannot be resolved on melodic.
This makes an error on `rosdep install` without `-r` option:
https://app.travis-ci.com/github/start-jsk/jsk_apc/jobs/615633458

This PR fixes that error by using snapshot of rosdep list on melodic as well as kinetic and under.
Result:
https://app.travis-ci.com/github/start-jsk/jsk_apc/jobs/616059276
Of course, adding `-r` option to `rosdep install` is another solution, but I think it is good time to use snapshot because melodic is EOL and no longer maintained on rosdistro:
https://github.com/ros/rosdistro/pull/39223#issuecomment-1861909367

### Minor fixes
- Include snapshot of rosdep list in this repository to increase portability of this repository
  - Otherwise we have to create a github gist every time when we have to create a new snapshot

### CODE REVIEW

**Comment by pazeshun** [comment]
@k-okada CI passed, could you review this?
One concern is that this PR may break backward compatibility and we may need to add changes to CI yamls of each repository like the following:
https://github.com/jsk-ros-pkg/jsk_travis/pull/457/commits/8d36659a7869592d8f20f85076c0b32f266e4df6
I searched code under jsk-ros-pkg and start-jsk:
https://github.com/search?q=org%3Ajsk-ros-pkg+%22mkdir+.travis%22&type=code
https://github.com/search?q=org%3Astart-jsk+%22mkdir+.travis%22&type=code
and I currently think we do not have such case.
But please tell me if I am wrong.

**Comment by pazeshun** [comment]
@k-okada Thank you! Could release this as 0.5.27?

**Comment by k-okada** [comment]
Sorry for the delay. I tried to release it right after the merge, but forgot all about it.

**Comment by pazeshun** [comment]
Thank you for releasing!

**Pull request merged**
