### PR TITLE
Use `--no-deps` to limit packages to tests

### LINKED ISSUE #142: Do not run tests for other packages
`catkin run_tests [package]` run tests for all the (dependent) packages in workspace.
In order to disable test in them, need to use `catkin config --blacklist` or `catkin config --whitelist`

### PR DESCRIPTION
**Pull request by garaemon**
closes #142

### CODE REVIEW

**Comment by garaemon** [comment]
Use `--no-deps` instead of `--whitelist`

**Comment by wkentaro** [comment]
+1

**Comment by garaemon** [comment]
```
####
#### Running command: "make run_tests jsk_travis --no-deps -j8 --" in "/home/travis/ros/ws_jsk_travis/build"
####
make: unrecognized option '--no-deps'
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from commands.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any commands; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no commands; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo commands.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.
This program built for x86_64-pc-linux-gnu
Report bugs to <bug-make@gnu.org>
Invoking "make run_tests jsk_travis --no-deps -j8 --" failed
```

**Comment by garaemon** [comment]
Changed location of `--no-deps`

**Comment by garaemon** [comment]
`catkin_make` does not have `--no-deps` option

**Comment by garaemon** [comment]
Removed `--no-deps` option if `USE_CATKIN_MAKE=true`

**Pull request merged**
