### PR TITLE
writing result to wrong place seems to be solved?

### PR DESCRIPTION
**Pull request by k-okada**
this might be dangerous, may fail in many repsitories....

### CODE REVIEW

**Comment by wkentaro** [comment]
@k-okada 
Test passes on *jsk_common* and *jsk_recognition*.
* https://github.com/jsk-ros-pkg/jsk_common/pull/1242
* https://github.com/jsk-ros-pkg/jsk_recognition/pull/1333

**Comment by k-okada** [comment]
could you check on jsk_roseus too?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada It fails if on jsk_roseus. https://github.com/jsk-ros-pkg/jsk_roseus/pull/406

**Comment by k-okada** [comment]
it passed on jsk_roseus  https://github.com/jsk-ros-pkg/jsk_roseus/pull/412

**Comment by k-okada** [comment]
ok, merged and bump version 0.2.0, which may fail test where previously passed

**Pull request merged**
