### PR TITLE
Fix ignored rosdep option in 'rosdep-install.sh'

### PR DESCRIPTION
**Pull request by wkentaro**
Closes https://github.com/jsk-ros-pkg/jsk_travis/issues/265

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this, ASAP.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
After this is merged. Please release next version.

**Comment by k-okada** [comment]
released 0.4.8

**Pull request merged**
