### PR TITLE
Don't use HTTP proxy for HTTPS urls for apt-cacher-ng

### PR DESCRIPTION
**Pull request by pazeshun**
To fix https://github.com/jsk-ros-pkg/jsk_travis/pull/388#issuecomment-549735323 and https://github.com/start-jsk/rtmros_common/pull/1077#issuecomment-549629846

### CODE REVIEW

**Comment by pazeshun** [comment]
`USE_JENKINS=true TEST_GAZEBO=true ROS_DISTRO=indigo`:
```
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="2" time="1236.852">
  <testcase classname="rostest.runner.RosTest" name="testgazebo_camera_sanity_checker" time="1222.0117">
    <error type="RLTestTimeoutException">max time [300.0s] allotted for test [gazebo_camera_sanity_checker] of type [rostest/hztest]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
    </error>
  </testcase>
```

**Comment by pazeshun** [comment]
Test in jenkins currently seems very slow...

**Comment by pazeshun** [comment]
Increasing time limit to 600 sec doesn't work, but whole test time became almost 50 minutes.
So I have to try another solution, but I have no idea...
```
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="2" time="2431.358">
  <testcase classname="rostest.runner.RosTest" name="testgazebo_camera_sanity_checker" time="2416.4189">
    <error type="RLTestTimeoutException">max time [600.0s] allotted for test [gazebo_camera_sanity_checker] of type [rostest/hztest]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
    </error>
  </testcase>
```

**Comment by pazeshun** [comment]
Travis passed. @k-okada Please review this.

### Why this PR is needed
Currently, `/etc/apt/sources.list` has https URLs after [dist-upgrade in Trusty docker](https://github.com/jsk-ros-pkg/jsk_travis/blob/0.5.5/docker/Dockerfile.ros-ubuntu:14.04#L3).
(Due to https://launchpad.net/ubuntu/trusty/+package/apt-transport-https? I'm not sure...)
However, `apt-cacher-ng` doesn't support https (see https://matoken.org/blog/2019/07/19/direct-access-to-https-repository-with-apt-cacher-ng/).

Therefore, I change `apt-cacher-ng` to let https connection pass through (without caching).
I follow https://github.com/sameersbn/docker-apt-cacher-ng/tree/3.1#usage because that method has readability.

To cache https, we have to rewrite URLs in `/etc/apt/sources.list` manually.
https://www.unix-ag.uni-kl.de/~bloch/acng/html/howtos.html#ssluse
I think this is too dirty, and should be avoided.

**Comment by pazeshun** [comment]
> Currently, `/etc/apt/sources.list` has https URLs after [dist-upgrade in Trusty docker](https://github.com/jsk-ros-pkg/jsk_travis/blob/0.5.5/docker/Dockerfile.ros-ubuntu:14.04#L3).

This is confirmed by the following procedure:
```
$ sudo docker pull ros:indigo-ros-base
indigo-ros-base: Pulling from library/ros
a7344f52cb74: Pull complete 
515c9bb51536: Pull complete 
e1eabe0537eb: Pull complete 
4701f1215c13: Pull complete 
5d696f48ae60: Pull complete 
f52975d1d499: Pull complete 
16a9feb12c63: Pull complete 
53a9587660aa: Pull complete 
fa6b9095725f: Pull complete 
624f0ce04189: Pull complete 
a2eb5ed02341: Pull complete 
44d0e8d9331b: Pull complete 
Digest: sha256:9f49a6e10a36119b58f1297f96ca0580fad411b7d5a77b7fd908ac1d20efca6e
Status: Downloaded newer image for ros:indigo-ros-base
$ sudo docker run -it ros:indigo-ros-base /bin/bash
root@eabb46e7af24:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
root@eabb46e7af24:/# sudo apt-get update
Get:1 http://snapshots.ros.org trusty InRelease [12.3 kB]
Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]           
Get:3 http://snapshots.ros.org trusty/main amd64 Packages [819 kB]             
Ign http://archive.ubuntu.com trusty InRelease                                 
Get:4 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]             
Get:5 http://security.ubuntu.com trusty-security/main amd64 Packages [1032 kB] 
Get:6 http://archive.ubuntu.com trusty-backports InRelease [65.9 kB]           
Get:7 http://security.ubuntu.com trusty-security/restricted amd64 Packages [18.1 kB]
Get:8 http://security.ubuntu.com trusty-security/universe amd64 Packages [377 kB]
Get:9 http://archive.ubuntu.com trusty Release.gpg [933 B]                     
Get:10 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1460 kB]
Get:11 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4730 B]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.4 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [671 kB]
Get:14 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [16.1 kB]
Get:15 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.7 kB]
Get:16 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:17 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.5 kB]
Get:18 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1392 B]
Get:19 http://archive.ubuntu.com trusty Release [58.5 kB]                      
Get:20 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]          
Get:21 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]    
Get:22 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]      
Get:23 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]     
Fetched 14.3 MB in 16s (843 kB/s)                                              
Reading package lists... Done
root@eabb46e7af24:/# sudo apt-get dist-upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  apt-transport-https python3-pkg-resources python3-yaml
The following packages will be upgraded:
  apt apt-utils libapt-inst1.5 libapt-pkg4.12 ubuntu-advantage-tools
5 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2036 kB of archives.
After this operation, 1037 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libapt-pkg4.12 amd64 1.0.1ubuntu2.24 [646 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apt amd64 1.0.1ubuntu2.24 [962 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libapt-inst1.5 amd64 1.0.1ubuntu2.24 [58.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apt-utils amd64 1.0.1ubuntu2.24 [172 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-yaml amd64 3.10-4ubuntu0.1 [92.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-pkg-resources all 3.3-1ubuntu2 [31.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apt-transport-https amd64 1.0.1ubuntu2.24 [25.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main ubuntu-advantage-tools amd64 19.6~ubuntu14.04.3 [47.3 kB]
Fetched 2036 kB in 8s (236 kB/s)                                               
(Reading database ... 44437 files and directories currently installed.)
Preparing to unpack .../libapt-pkg4.12_1.0.1ubuntu2.24_amd64.deb ...
Unpacking libapt-pkg4.12:amd64 (1.0.1ubuntu2.24) over (1.0.1ubuntu2.23) ...
Setting up libapt-pkg4.12:amd64 (1.0.1ubuntu2.24) ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
(Reading database ... 44437 files and directories currently installed.)
Preparing to unpack .../apt_1.0.1ubuntu2.24_amd64.deb ...
Unpacking apt (1.0.1ubuntu2.24) over (1.0.1ubuntu2.23) ...
Setting up apt (1.0.1ubuntu2.24) ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
(Reading database ... 44437 files and directories currently installed.)
Preparing to unpack .../libapt-inst1.5_1.0.1ubuntu2.24_amd64.deb ...
Unpacking libapt-inst1.5:amd64 (1.0.1ubuntu2.24) over (1.0.1ubuntu2.23) ...
Preparing to unpack .../apt-utils_1.0.1ubuntu2.24_amd64.deb ...
Unpacking apt-utils (1.0.1ubuntu2.24) over (1.0.1ubuntu2.23) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../python3-yaml_3.10-4ubuntu0.1_amd64.deb ...
Unpacking python3-yaml (3.10-4ubuntu0.1) ...
Selecting previously unselected package python3-pkg-resources.
Preparing to unpack .../python3-pkg-resources_3.3-1ubuntu2_all.deb ...
Unpacking python3-pkg-resources (3.3-1ubuntu2) ...
Selecting previously unselected package apt-transport-https.
Preparing to unpack .../apt-transport-https_1.0.1ubuntu2.24_amd64.deb ...
Unpacking apt-transport-https (1.0.1ubuntu2.24) ...
Preparing to unpack .../ubuntu-advantage-tools_19.6~ubuntu14.04.3_amd64.deb ...
Moving obsolete conffile /etc/update-motd.d/99-esm out of the way...
Unpacking ubuntu-advantage-tools (19.6~ubuntu14.04.3) over (10ubuntu0.14.04.3) ...
Setting up libapt-inst1.5:amd64 (1.0.1ubuntu2.24) ...
Setting up apt-utils (1.0.1ubuntu2.24) ...
Setting up python3-yaml (3.10-4ubuntu0.1) ...
Setting up python3-pkg-resources (3.3-1ubuntu2) ...
Setting up apt-transport-https (1.0.1ubuntu2.24) ...
Setting up ubuntu-advantage-tools (19.6~ubuntu14.04.3) ...
Installing new version of config file /etc/apt/apt.conf.d/51ubuntu-advantage-esm ...
Removing obsolete conffile /etc/update-motd.d/99-esm ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
root@eabb46e7af24:/# sudo apt-get update
Hit http://snapshots.ros.org trusty InRelease
Hit http://snapshots.ros.org trusty/main amd64 Packages                
Ign http://archive.ubuntu.com trusty InRelease                
Hit http://security.ubuntu.com trusty-security InRelease      
Hit http://archive.ubuntu.com trusty-updates InRelease                         
Hit http://security.ubuntu.com trusty-security/main amd64 Packages             
Get:1 https://esm.ubuntu.com trusty-infra-security InRelease                   
Hit http://archive.ubuntu.com trusty-backports InRelease                       
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages       
Get:2 https://esm.ubuntu.com trusty-infra-updates InRelease                    
Hit http://archive.ubuntu.com trusty Release.gpg                               
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages         
Get:3 https://esm.ubuntu.com trusty-infra-security/main amd64 Packages         
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages               
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages       
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages         
Get:4 https://esm.ubuntu.com trusty-infra-updates/main amd64 Packages          
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages    
Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty Release                          
Hit http://archive.ubuntu.com trusty/main amd64 Packages
100% [Working]                                                      785100% [Packages 0 B]                                                 785100% [Connecting to archive.ubuntu.com (91.189.88.174)]             785                                                                       Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
100% [Working]                                                      785                                                                       100% [Connecting to archive.ubuntu.com (91.189.88.174)]             785                                                                       Hit http://archive.ubuntu.com trusty/universe amd64 Packages
100% [Connecting to archive.ubuntu.com (91.189.88.174)]             785                                                                       Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages        
100% [Packages 7589 kB]                                             785100% [Working]                                                      785100% [Packages 0 B]                                                 785100% [Working]                                                      785                                                                       Fetched 228 kB in 7s (30.5 kB/s)
Reading package lists... Done
```

**Comment by k-okada** [comment]
Seems ok, merge if https://travis-ci.org/start-jsk/rtmros_common/builds/607578806?utm_source=github_status&utm_medium=notification passed

**Comment by pazeshun** [comment]
@k-okada Could you merge this?
Travis test of https://github.com/start-jsk/rtmros_common/pull/1077 finally passed.

**Comment by pazeshun** [comment]
Please also release this.

**Comment by pazeshun** [comment]
Thank you!

**Pull request merged**
