### PR TITLE
suppress test warning in catkin run_tests

### PR DESCRIPTION
**Pull request by knorth55**
this PR suppress warning in `catkin run_tests`.
this trick is introduced in https://github.com/catkin/catkin_tools/issues/405#issuecomment-573753780

without this PR, travis fails because of long log output.
https://app.travis-ci.com/github/start-jsk/jsk_apc/builds/251296485

### CODE REVIEW

**Comment by knorth55** [comment]
kindly ping

**Comment by pazeshun** [comment]
After https://github.com/jsk-ros-pkg/jsk_travis/pull/455#issuecomment-1573136484 is fixed, I want to update this branch (because travis is currently super slow, we should avoid updating until #456 and other follow-up PRs are finished).

**Comment by pazeshun** [comment]
@k-okada Could you review this PR?
If this PR is OK, please merge and release it.

**Comment by k-okada** [comment]
@pazeshun released https://github.com/jsk-ros-pkg/jsk_travis/releases/tag/0.5.26

**Pull request merged**
